use nu_scripts/custom-completions/bat/bat-completions.nu *
use nu_scripts/custom-completions/cargo-make/cargo-make-completions.nu *
use nu_scripts/custom-completions/composer/composer-completions.nu *
use nu_scripts/custom-completions/curl/curl-completions.nu *
use nu_scripts/custom-completions/docker/docker-completions.nu *
use nu_scripts/custom-completions/flutter/flutter-completions.nu *
use nu_scripts/custom-completions/git/git-completions.nu *
use nu_scripts/custom-completions/just/just-completions.nu *
use nu_scripts/custom-completions/less/less-completions.nu *
use nu_scripts/custom-completions/make/make-completions.nu *
use nu_scripts/custom-completions/mysql/mysql-completions.nu *
use nu_scripts/custom-completions/npm/npm-completions.nu *
use nu_scripts/custom-completions/pass/pass-completions.nu *
use nu_scripts/custom-completions/reflector/reflector-completions.nu *
use nu_scripts/custom-completions/rg/rg-completions.nu *
use nu_scripts/custom-completions/rustup/rustup-completions.nu *
use nu_scripts/custom-completions/scoop/scoop-completions.nu *
use nu_scripts/custom-completions/tar/tar-completions.nu *
use nu_scripts/custom-completions/typst/typst-completions.nu *
use nu_scripts/custom-completions/winget/winget-completions.nu *
use nu_scripts/custom-completions/yarn/yarn-v4-completions.nu *
use nu_scripts/custom-completions/zellij/zellij-completions.nu *
