theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[editor.indent-guides]
render = false
character = "·"

[editor.lsp]
display-messages = true
display-inlay-hints = true
