[user]
name = "DustVoice"
email = "info@dustvoice.de"

[ui]
editor = "nvim"

[signing]
sign-all = true
backend = "ssh"
key = "~/.ssh/id_ed25519_sk.pub"

[signing.ssh.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"
