[user]
name = "DustVoice"
email = "info@dustvoice.de"

[ui]
editor = "nvim"
default-command = "log"
diff-editor = ":builtin"

[signing]
sign-all = true
backend = "gpg"
key = "7A9CA430D426100E"

[signing.ssh.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"
