[user]
name = "DustVoice"
email = "info@dustvoice.de"

[ui]
editor = "nvim"
default-command = "log"
diff-editor = ":builtin"

[signing]
sign-all = true
backend = "gpg"
key = "7A9CA430D426100E"

[signing.ssh.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
  "-c",
  "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c",
  "JJDiffConflicts!",
  "$output",
  "$base",
  "$left",
  "$right",
]
merge-tool-edits-conflict-markers = true

[merge-tools.vimdiff]
merge-args = [
  "-f",
  "-d",
  "$output",
  "-M",
  "$left",
  "$base",
  "$right",
  "-c",
  "wincmd J",
  "-c",
  "set modifiable",
  "-c",
  "set write",
]
program = "vim"
merge-tool-edits-conflict-markers = true
