# ~/.config/starship.toml
palette = "catppuccin_macchiato"

add_newline = true
scan_timeout = 30
command_timeout = 500

format = '$all'

continuation_prompt = ">>>"

[aws]
symbol = "[AWS](bold bg:yellow fg:black) "
style = "bold yellow"

[character]
success_symbol = "[>](bold purple)"
error_symbol = "[X](bold red)"
vimcmd_symbol = "[:](bold green)"
vimcmd_replace_symbol = "[s](bold red)"
vimcmd_replace_one_symbol = "[s](bold red)"
vimcmd_visual_symbol = "[/](bold yellow)"

[cmake]
symbol = "[CMake](bold bg:blue fg:white) "
style = "bold blue"

[conda]
symbol = "[Conda](bold bg:green fg:black) "
style = "bold green"

[crystal]
symbol = "[Crystal](bold bg:red fg:white) "
style = "bold red"

[dart]
symbol = "[Dart](bold bg:blue fg:white) "
style = "bold blue"

[deno]
symbol = "[Deno](bold bg:green fg:black) "
style = "green bold"

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = ".../"

[docker_context]
symbol = "[Docker](bold bg:blue fg:white) "
style = "blue bold"

[dotnet]
format = "[[.NET](bold bg:blue fg:white) ($version )([target](bold bg:blue fg:white) $tfm )]($style)"
symbol = ""
style = "bold blue"

[elixir]
symbol = "[Elixir](bold bg:purple fg:black) "
style = "bold purple"

[elm]
symbol = "[Elm](bold bg:cyan fg:black) "
style = "cyan bold"

[erlang]
symbol = "[Erlang](bold bg:red fg:white) "
style = "bold red"

[gcloud]
symbol = "[G-Cloud](bold bg:blue fg:white) "
style = "bold blue"

[git_branch]
format = "on [$symbol$branch( \\($remote_name/$remote_branch\\))]($style) "
symbol = "[git](bold bg:purple fg:black) "
style = "bold purple"
truncation_length = 9223372036854775805
truncation_symbol = "..."

[git_commit]
style = "bold green"
tag_symbol = " [tag](bold bg:green fg:black) "

[git_status]
ignore_submodules = true
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[golang]
symbol = "[go](bold bg:cyan fg:black) "
style = "bold cyan"

[helm]
symbol = "[Helm](bold bg:white fg:black) "

[hostname]
trim_at = ""

[java]
symbol = "[Java](dimmed bg:red fg:white) "
style = "red dimmed"

[jobs]
symbol = "+"

[julia]
symbol = "[Julia](bold bg:purple fg:black) "
style = "bold purple"

[kotlin]
symbol = "[Kotlin](bold bg:blue fg:white) "
style = "bold blue"

[kubernetes]
symbol = "[Kubernetes](bold bg:cyan fg:black) "
style = "cyan bold"

[lua]
symbol = "[Lua](bold bg:blue fg:white) "
style = "bold blue"

[memory_usage]
symbol = "[Mem](bold bg:white fg:black)"
style = "bold dimmed white"

[hg_branch]
symbol = "[hg](bold bg:purple fg:black) "
style = "bold purple"
truncation_length = 9223372036854775805
truncation_symbol = "..."

[nim]
symbol = "[Nim](bold bg:yellow fg:black) "
style = "bold yellow"

[nix_shell]
symbol = "[nix_sh](bold bg:blue fg:white) "
style = "bold blue"

[nodejs]
symbol = "[node](bold bg:green fg:black) "
style = "bold green"

[ocaml]
symbol = "[Ocaml](bold bg:yellow fg:black) "
style = "bold yellow"

[openstack]
symbol = "[Openstack](bold bg:yellow fg:black) "
style = "bold yellow"

[package]
format = "is [$symbol$version]($style) "
symbol = "[pkg](bold bg:red fg:white) "
style = "bold red"

[perl]
symbol = "[perl](bold bg:149 fg:white) "
style = "bold 149"

[php]
symbol = "[php](bold bg:147 fg:white) "
style = "147 bold"

[purescript]
symbol = "[Purescript](bold bg:white fg:black)=> "
style = "bold white"

[python]
symbol = "[Python](bold bg:yellow fg:black) "
style = "yellow bold"

[rlang]
symbol = "[Rlang](bold bg:blue fg:white)"
style = "blue bold"

[red]
symbol = "[Red](bold bg:red fg:white) "
style = "red bold"

[ruby]
symbol = "[Ruby](bold bg:red fg:white) "
style = "bold red"

[rust]
format = "via [$symbol($version )]($style)"
symbol = "[Cargo](bold bg:red fg:white) "
style = "bold red"

[scala]
symbol = "[Scala](dimmed bg:red fg:white) "
style = "red dimmed"

[shlvl]
symbol = "[Shlvl](bold bg:yellow fg:black) "
style = "bold yellow"

[singularity]
symbol = "[Singularity](bold dimmed bg:blue fg:white)"
style = "bold dimmed blue"

[status]
symbol = "[Status](bold bg:red fg:white)"
style = "bold red"

[swift]
symbol = "[Swift](bold bg:202 fg:white) "
style = "bold 202"

[terraform]
symbol = "[Terraform](bold bg:105 fg:white)"
style = "bold 105"

[username]

[vagrant]
symbol = "[Vagrant](bold bg:cyan fg:black) "
style = "cyan bold"

[vlang]
symbol = "[Vlang](bold bg:blue fg:white) "
style = "blue bold"

[vcsh]
symbol = "[Vcsh](bold bg:yellow fg:black)"

[zig]
style = "bold yellow"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
