unstable_features = true

binop_separator = "Front"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

brace_style = "SameLineWhere"

color = "Auto"

combine_control_expr = true

comment_width = 80

condense_wildcard_suffixes = true

control_brace_style = "AlwaysSameLine"

disable_all_formatting = false

edition = "2021"

empty_item_single_line = true

enum_discrim_align_threshold = 0

error_on_line_overflow = false

error_on_unformatted = false

fn_args_layout = "Tall"

fn_single_line = false

force_explicit_abi = true

force_multiline_blocks = false

format_code_in_doc_comments = false

format_macro_matchers = false

format_macro_bodies = true

format_strings = false

hard_tabs = false

hide_parse_errors = false

ignore = []

imports_indent = "Block"

imports_layout = "Mixed"

indent_style = "Block"

inline_attribute_width = 0

license_template_path = ""

match_arm_blocks = true

match_arm_leading_pipes = "Never"

match_block_trailing_comma = false

max_width = 100

merge_derives = true

imports_granularity = "Preserve"

merge_imports = false

newline_style = "Auto"

normalize_comments = false

normalize_doc_attributes = false

overflow_delimited_expr = false

remove_nested_parens = true

reorder_impl_items = false

reorder_imports = true

group_imports = "Preserve"

reorder_modules = true

report_fixme = "Never"

report_todo = "Never"

skip_children = false

space_after_colon = true

space_before_colon = false

spaces_around_ranges = false

struct_field_align_threshold = 0

struct_lit_single_line = true

tab_spaces = 4

trailing_comma = "Vertical"

trailing_semicolon = true

type_punctuation_density = "Wide"

use_field_init_shorthand = false

use_small_heuristics = "Default"

use_try_shorthand = false

version = "Two"

where_single_line = false

wrap_comments = false
