theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[keys.normal]
g = { "left" = "goto_line_start", "right" = "goto_line_end", "up" = "goto_file_start", "down" = "goto_last_line" }

[keys.normal.space.l]
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
j = [":new", ":insert-output lazyjj", ":buffer-close!", ":redraw"]
