#!/usr/bin/env zsh

if [[ -f $HOME/.zsh_alias ]]; then
    source $HOME/.zsh_alias
fi

fallback_font="Hack:size=10:antialias=true:autohint=true"
font=""
if [ -x $(command -v xgetres) ]; then
    font=$(xgetres font || echo $fallback_font);
else
    font=$fallback_font;
fi

command_to_run=$({ alias | awk '{split($0,alias,"="); print alias[1];}' ; dmenu_path ; } | sort | dmenu -i -fn $font -nb "#282a36" -nf "#f8f8f2" -sb "#44475a" -sf "#f8f8f2" "$@")

eval ${command_to_run} &
