#!/bin/sh

sxhkd &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d \~
done

bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled manage=on

nitrogen --restore &
/usr/lib/xfce-polkit/xfce-polkit &
xss-lock -- i3lock -n -e -c 333333 &

$HOME/.config/polybar/launch.sh
