[symlinks]
"config.nu" = "C:\\Users\\Holland/AppData/Roaming/nushell/config.nu"
"env.nu" = "C:\\Users\\Holland/AppData/Roaming/nushell/env.nu"
"gpg-agent.conf" = "C:\\Users\\Holland/AppData/Roaming/gnupg/gpg-agent.conf"
"gpg.conf" = "C:\\Users\\Holland/AppData/Roaming/gnupg/gpg.conf"
known_hosts = "C:\\Users\\Holland/.ssh/known_hosts"
"plugins/nushell/nu_scripts/themes/nu-themes/catppuccin-mocha.nu" = "C:\\Users\\Holland/AppData/Roaming/nushell/scripts/nu_scripts/themes/nu-themes/catppuccin-mocha.nu"
"plugins/nvim\\.git" = "C:\\Users\\Holland/AppData/Local/nvim\\.git"
"plugins/nvim\\.gitignore" = "C:\\Users\\Holland/AppData/Local/nvim\\.gitignore"
"plugins/nvim\\.neoconf.json" = "C:\\Users\\Holland/AppData/Local/nvim\\.neoconf.json"
"plugins/nvim\\.stylua.toml" = "C:\\Users\\Holland/AppData/Local/nvim\\.stylua.toml"
"plugins/nvim\\README.md" = "C:\\Users\\Holland/AppData/Local/nvim\\README.md"
"plugins/nvim\\init.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\init.lua"
"plugins/nvim\\lua\\community.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\community.lua"
"plugins/nvim\\lua\\lazy_setup.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\lazy_setup.lua"
"plugins/nvim\\lua\\plugins\\astrocore.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\astrocore.lua"
"plugins/nvim\\lua\\plugins\\astrolsp.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\astrolsp.lua"
"plugins/nvim\\lua\\plugins\\astroui.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\astroui.lua"
"plugins/nvim\\lua\\plugins\\mason.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\mason.lua"
"plugins/nvim\\lua\\plugins\\none-ls.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\none-ls.lua"
"plugins/nvim\\lua\\plugins\\treesitter.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\treesitter.lua"
"plugins/nvim\\lua\\plugins\\user.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\plugins\\user.lua"
"plugins/nvim\\lua\\polish.lua" = "C:\\Users\\Holland/AppData/Local/nvim\\lua\\polish.lua"
"plugins/nvim\\neovim.yml" = "C:\\Users\\Holland/AppData/Local/nvim\\neovim.yml"
"plugins/nvim\\selene.toml" = "C:\\Users\\Holland/AppData/Local/nvim\\selene.toml"
ssh = "C:\\Users\\Holland/.ssh/config"
sshcontrol = "C:\\Users\\Holland/AppData/Roaming/gnupg/sshcontrol"
"starship.toml" = "C:\\Users\\Holland/.config/starship.toml"
"wezterm.lua" = "C:\\Users\\Holland/.config/wezterm/wezterm.lua"

[templates]
gitconfig = "C:\\Users\\Holland/.gitconfig"
