[alacritty.files]
"alacritty.toml" = "~/AppData/Roaming/alacritty/alacritty.toml"
"plugins/catppuccin/alacritty/catppuccin-macchiato.toml" = "~/AppData/Roaming/alacritty/catppuccin-macchiato.toml"

[gnupg.files]
"gpg-agent.conf" = "~/AppData/Roaming/gnupg/gpg-agent.conf"
"gpg.conf" = "~/AppData/Roaming/gnupg/gpg.conf"
sshcontrol = "~/AppData/Roaming/gnupg/sshcontrol"

[helix.files]
"helix.toml" = "~/AppData/Roaming/helix/config.toml"
"languages.toml" = "~/AppData/Roaming/helix/languages.toml"

[nushell.files]
"config.nu" = "~/AppData/Roaming/nushell/config.nu"
"env.nu" = "~/AppData/Roaming/nushell/env.nu"

[nushell.files."plugins/nushell/nu_scripts/themes/nu-themes/catppuccin-mocha.nu"]
target = "~/AppData/Roaming/nushell/scripts/nu_scripts/themes/nu-themes/catppuccin-mocha.nu"
type = "symbolic"

[nvim.files."plugins/nvim"]
recurse = false
target = "~/AppData/Local/nvim"
type = "symbolic"
